export const characters = [
  {
    id: "belut",
    nome: "Belut",
    immagine: "/personaggi/belut.jpeg",
    titolo: "Master in sensoristica olfattiva avanzata",
    colore: "#58d68d",
  },
  {
    id: "clari",
    nome: "Clari",
    immagine: "/personaggi/clari.jpeg",
    titolo: "Master in sfondamento di cancelli",
    colore: "#ff4fd8",
  },
  {
    id: "conti",
    nome: "Conti",
    immagine: "/personaggi/conti.jpeg",
    titolo: "Master in collezionismo di cagate alternative in autostrada",
    colore: "#ffb84d",
  },
  {
    id: "fede",
    nome: "Fede",
    immagine: "/personaggi/fede.jpeg",
    titolo: "Master in gestione dell'ansia a carnevale",
    colore: "#7c7cff",
  },
  {
    id: "fra-nicoli",
    nome: "Fra Nicoli",
    immagine: "/personaggi/fra nicoli.jpeg",
    titolo: "Master in gossip finding and reveal",
    colore: "#ef476f",
  },
  {
    id: "fra",
    nome: "Fra",
    immagine: "/personaggi/fra.jpeg",
    titolo: "Master in cosa nostra e gestione dei pizzi del vicinato",
    colore: "#06d6a0",
  },
  {
    id: "gabri",
    nome: "Gabri",
    immagine: "/personaggi/gabri.jpeg",
    titolo: "Master in invenzione di scuse per non uscire di casa",
    colore: "#4cc9f0",
  },
  {
    id: "ghila",
    nome: "Ghila",
    immagine: "/personaggi/ghila.jpeg",
    titolo: "Master in drunkness management",
    colore: "#f72585",
  },
  {
    id: "greta",
    nome: "Greta",
    immagine: "/personaggi/greta.jpeg",
    titolo: "Master nel trovarsi l'unica donna in mezzo a 3 cugini idioti",
    colore: "#ffd166",
  },
  {
    id: "loris",
    nome: "Loris",
    immagine: "/personaggi/loris.jpeg",
    titolo: "Master nell'uscire di casa a orari improponibili",
    colore: "#00bbf9",
  },
  {
    id: "mickybi",
    nome: "Mickybi",
    immagine: "/personaggi/mickybi.jpeg",
    titolo: "Master in collezionismo di sboccate alternative",
    colore: "#9b5de5",
  },
  {
    id: "vale",
    nome: "Vale",
    immagine: "/personaggi/vale.jpeg",
    titolo: "Master in Pijama-driven outfit",
    colore: "#f15bb5",
  },
  {
    id: "vegio-michi",
    nome: "Vegio Michi",
    immagine: "/personaggi/vegio michi.jpeg",
    titolo: "Master in joint rolling and quality check",
    colore: "#80ed99",
  },
  {
    id: "vegio",
    nome: "Vegio",
    immagine: "/personaggi/vegio.jpeg",
    titolo: "Master nel mostrare il proprio deretano al pubblico",
    colore: "#f77f00",
  },
];
